### PR TITLE
Implement method chaining for PluginMetadata

### PR DESCRIPTION
**Pull request by kmecpp**
Also adds methods for adding multiple authors or dependencies

### CODE REVIEW

**Comment by Minecrell** [comment]
That would be nice to have, but I think it's not worth breaking all existing users just to get method chaining.

**Comment by kmecpp** [comment]
Shouldn't it be backwards compatible? Just added a return type to the methods

**Comment by Minecrell** [comment]
It is source compatible but unfortunately not binary compatible. Java adds the return type in the compiled bytecode.

**Comment by Minecrell** [comment]
Yes, but right now I'm not sure if or when there is going to be a breaking update for this library, it doesn't follow SpongeAPI's normal versioning. It seems wrong to me to break compatibility just for a bit of syntax sugar. Maybe when we have some other breaking changes as well?

For now, can you submit another PR with only the new methods (without method chaining for consistency), so we can merge that earlier?

**Comment by Zidane** [comment]
Thanks for the work on this but I am closing this PR. We have no plans to move forward with the mcmod-info metadata format and Sponge has it's own starting in 1.14 and above. The way those classes are constructed, they are immutable. If anything, the builder classes should take an existing object as a copyInto.

Again thanks and apologies for the gigantic wait on this either way.

**Pull request closed without merging**
